  lab_5.2.cpp
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(38,1): warning C4297: wholePart2: ожидается, что функция не будет выдавать исключения, но она это делает
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(38,1): message : для функции указан атрибут __declspec(nothrow), throw(), noexcept(true) или noexcept
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(42,58): warning C4290: спецификация исключений C++ игнорируется, кроме случая, когда указывается, что функция не является __declspec(nothrow)
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(48,59): warning C4290: спецификация исключений C++ игнорируется, кроме случая, когда указывается, что функция не является __declspec(nothrow)
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(54,59): warning C4290: спецификация исключений C++ игнорируется, кроме случая, когда указывается, что функция не является __declspec(nothrow)
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(60,57): warning C4290: спецификация исключений C++ игнорируется, кроме случая, когда указывается, что функция не является __declspec(nothrow)
E:\Політех\ооп\5\lab_5.2\lab_5.2\lab_5.2.cpp(114,3): warning C4286: E: перехвачено базовым классом ("std::exception") в строке 111
  lab_5.2.vcxproj -> E:\Політех\ооп\5\lab_5.2\x64\Debug\lab_5.2.exe
